[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    preset = "desktop" # Optionally run Lighthouse using a desktop configuration

[[headers]]
  for = "/*"
  [headers.values]
    // Content-Security-Policy-Report-Only = "default-src https:; report-to /csp-violation-report-endpoint/"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Frame-Options = "DENY"